openapi: 3.0.3
info:
  title: S2 Customer API
  description: 客戶管理 API - 用於 Testcontainers PoC S2 多儲存層場景
  version: 1.0.0
  contact:
    name: Testcontainers PoC Team

servers:
  - url: http://localhost:8081
    description: Local development

paths:
  /api/customers:
    post:
      summary: 建立客戶
      operationId: createCustomer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
      responses:
        '201':
          description: 客戶建立成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: 請求格式錯誤
        '409':
          description: 電子郵件已存在

  /api/customers/{customerId}:
    get:
      summary: 查詢單一客戶
      operationId: getCustomer
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 客戶詳情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
          headers:
            X-Cache-Hit:
              description: 是否命中快取
              schema:
                type: boolean
        '404':
          description: 客戶不存在

    put:
      summary: 更新客戶
      operationId: updateCustomer
      tags:
        - Customers
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerRequest'
      responses:
        '200':
          description: 客戶更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: 客戶不存在

  /api/customers/search:
    get:
      summary: 全文搜尋客戶
      operationId: searchCustomers
      tags:
        - Customers
      parameters:
        - name: q
          in: query
          required: true
          description: 搜尋關鍵字
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 搜尋結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerSearchResponse'

components:
  schemas:
    CreateCustomerRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          maxLength: 100
          example: "王小明"
        email:
          type: string
          format: email
          example: "wang@example.com"
        phone:
          type: string
          maxLength: 20
          example: "0912345678"
        address:
          type: string
          maxLength: 500
          example: "台北市信義區信義路五段7號"

    UpdateCustomerRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        phone:
          type: string
          maxLength: 20
        address:
          type: string
          maxLength: 500

    CustomerResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        address:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CustomerSearchResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CustomerResponse'
        totalHits:
          type: integer
          format: int64
        page:
          type: integer
        size:
          type: integer
