package com.example.s8;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.example.s8.dto.OrderDto;
import com.example.s8.service.OrderService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import java.time.Instant;
import java.util.UUID;

/**
 * Provider Pact test that verifies the provider implementation against the contract.
 * Uses Spring Boot's embedded server to run the actual provider.
 *
 * This test loads the pact file generated by the consumer test and verifies
 * that the provider (Order API) satisfies all consumer expectations.
 */
@ExtendWith(SpringExtension.class)
@SpringBootTest(
    classes = S8Application.class,
    webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT
)
@Provider("OrderProvider")
@PactFolder("build/pacts")
class OrderProviderPactIT {

    @LocalServerPort
    private int port;

    @Autowired
    private OrderService orderService;

    @BeforeEach
    void setUp(PactVerificationContext context) {
        if (context != null) {
            context.setTarget(new HttpTestTarget("localhost", port));
        }
        // Clear any existing orders before each test
        orderService.clearAll();
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        if (context != null) {
            context.verifyInteraction();
        }
    }

    /**
     * State handler: Sets up an order with the specified ID.
     * This is called before the verification of interactions that require this state.
     */
    @State("an order with ID 550e8400-e29b-41d4-a716-446655440000 exists")
    void setupOrderExists() {
        UUID orderId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        Instant now = Instant.now();
        OrderDto order = new OrderDto(orderId, "John Doe", "PENDING", now, now);
        orderService.addOrder(order);
    }

    /**
     * State handler: The order service is available for creating orders.
     * No special setup needed - the service is already running.
     */
    @State("the order service is available")
    void setupServiceAvailable() {
        // No special setup needed - service is already running
    }

    /**
     * State handler: No order exists with the specified ID.
     * Ensures the order store is empty for this test.
     */
    @State("no order exists with ID 00000000-0000-0000-0000-000000000000")
    void setupOrderNotExists() {
        // Clear any existing orders
        orderService.clearAll();
    }
}
